### ISSUE TITLE
Check for remaining packet size in case of process data with dynamic arrays not working for certain array sizes / packets

### ISSUE THREAD

**Issue by michaelkirsche** [T12z/TCNopen#1]
In the handling of dynamic arrays, a check is performed to find out if the (dynamic) array size of the element in question can fit in the rest of the available packet.
https://github.com/T12z/TCNopen/blob/816cd1b2accdffad42c4fdae642f3078b7e98881/trdp/spy/src/trdp_spy/packet-trdp_spy.c#L370

If the remainder is between 1 and 3, the test in line 370 will always be true and a wrong user data (expert info) will be written into the packet. This would (for example) be the case for a dataset containing a dynamic array followed by a single boolean or integer value.

Shouldn't the check be only true (not enough space left -> error) if the remainder is smaller than zero and false (thus enough space is left) for values equal or larger than zero?

Also, why check for `remainder < TRDP_FCS_LENGTH` here? If datasets are placed behind the headerFCS, the TVB offset is already pointing beyond them and the remaining length does not need to consider the TRDP FCS, or am I missing something?

Thanks in advance for your reply/feedback!

**Comment by T12z** [comment]
nice find!
yes, this is actually zombie code. see https://sourceforge.net/p/tcnopen/tickets/47/
When I refactored, I either forgot about it or was puzzled by the same questions, as you. And then forgot about it.

I changed the check to something more reasonable, though not really tested it. Commited to master. 

On a nosy side note, are you actually using variable length arrays?
At first I thought, nice feature, but had to realize they are causing me more troubles and overhead. Though I am only using process data. I never trialed any of the TCP / MD stuff.

**Comment by michaelkirsche** [comment]
Thanks for the quick feedback and for the hint with the dropping of the data FCS part.

And yes, we are trying out variable length arrays for datasets. For process data at the moment too.
What kind of troubles did you run into when using dynamic arrays?

**Comment by T12z** [comment]
At first, I found the length definition in an element before a bit clumsy. There is no actual syntax for it, just this use-case definition.

When I use process data, I do typically have an expectation of data to receive, which doesn't really change dynamically. In most cases I have to reserve the resources for the maximum amount of data anyways, so I don't save anything, other than for transport. In realtime systems I always have to reserve for the maximum case, so no saving at all. Unfortunately, there is no maximum length declaration for variable length arrays as far as I remember.

And, as far as I remember, arrays were only allowed in special cases. Something with last element only, though honestly, I really don't remember correctly. Maybe in MD only?? In any case, the wireshark dissector is quite liberal about this and will try to decode arrays anywhere, even if it is not conforming to the standards.
