### ISSUE TITLE
Endian read error in v4.x

### ISSUE THREAD

**Issue by marcelvanthoff** [T12z/TCNopen#10]
When opening a pcapng with TRDP data, the values are interpreted differently. As shown in the screenshot, the same capture in different versions of trdpspy shows different values.

Left is Wireshark v4.0.1 with the trdpspy v4.0. 
Right is Wireshark v3.8.6 with trdpspy v3.6. 
The sent double value is 120 (0x42F00000) and is correctly interpreted in v3.6.

Could it have to do with the commit of Georges?
https://github.com/T12z/TCNopen/commit/703621eb970dd5c7da7f5158233a6307191fec92

![endian changed](https://github.com/T12z/TCNopen/assets/1043823/f887cf49-28f4-430c-adce-2b0ed63b9d84)

**Comment by T12z** [comment]
Hej Marcel,
... quite potentially.
In your screenshot's wireshark status line we can see (left) that it does interpret with the little-endian logic. And right it does not, as it was not part of the plugin back in the days.

Just looking at the patch-code, the code-logic seems to be right. May be there is something wrong with the input parsing. I will check.
