### ISSUE TITLE
No rule to make target 'bld/output/-rel/vos_sock.o'

### ISSUE THREAD

**Issue by waarmond** [T12z/TCNopen#11]
I'm trying to build your TCNopen fork with gcc 13:
```
cd trdp
make clean libtrdp libtrdpap
```

`make: *** No rule to make target 'bld/output/-rel/vos_sock.o', needed by 'bld/output/-rel/libtrdp.a'.  Stop.`

**Comment by T12z** [comment]
I guess you used some `make LINUX_something` before running that command, as suggested by the [readme-makefile.txt](https://github.com/T12z/TCNopen/blob/master/trdp/readme-makefile.txt) or `make help` ?
Well I changed a few things in the Makefile of the main branch to let the whole build-system run more robust for me. Thus I never checked all the original build-configs. I probably forgot to propagate a variable used in the path ( .../?-rel/... ). Currently, only the configuration `make DEB_config` is kind of guaranteed to work from main branch. If it does not fullfil your needs, either modify it or use the upstream branch, or even try the upstream from sourceforge.

virgin `git clone` and `make bindeb-pkg` works for me on my Debian sid-system ... well, the build of the wireshark-plugin stalls in wireshark's headers - but that seems to be a different story :(
