### ISSUE TITLE
PD pull pattern exaxmple

### ISSUE THREAD

**Issue by daniele77** [T12z/TCNopen#2]
I need to write a simple application that answers with `Pp` to a periodic request `Pr` (PD pull pattern).
However, there is no documentation about it.
Where can I find an example of this?
Thank you very much.

**Comment by T12z** [comment]
Sorry, to be honest, I have gotten a little out of practice.
I just rgrepped the source and found trdp/test/diverse/pdPull.c  -- does that help, or do you need further hints?

In my repository I added a CPP wrapper for my XML-Session abstraction (https://github.com/T12z/TCNopen/blob/master/trdp/src/common/tau_xsession.hpp). I am using this in a Qt-Application to answer Requests. This app would be publically available, but not here on github. Yet, this is not a lean application to quickly play with.

**Comment by daniele77** [comment]
First of all, thank you for the answer.
I would need an example that responds with a `Pp`message to periodic `Pr` requests. 
The example `pdPull.c` in the library sources sends the periodic `Pr` requests, but I can't find an example of a responder. 
I tried tinkering with the APIs to send `Pp` messages but without success.
Any idea?

**Comment by T12z** [comment]
(Cleaning this issue up)
I am not that acquainted with upstream's examples - when and under what condition they work.
