### ISSUE TITLE
About macro VOS_MAX_SOCKET_CNT and VOS_MAX_MULTICAST_CNT

### ISSUE THREAD

**Issue by JiangLingJun** [T12z/TCNopen#6]
Hello, ask a question. Why define VOS_MAX_SOCKET_CNT 4 and VOS_MAX_MULTICAST_CNT 5? Can I modify to other value?

**Comment by T12z** [comment]
Did you have a look at trdp/src/vos/api/vos_sock.h ? 
I actually does give a short explanation and shows where/why it is a modifyable const.
