### ISSUE TITLE
When adapting lwip, the size compare will report an error in trdp_mdRecvUDPPacket

### ISSUE THREAD

**Issue by gagmeng** [T12z/TCNopen#9]
In lwip, it will return the total message length in recvmsg. So when adapting lwip, the size compare(size == sizeof(MD_HEADER_T)) will report an error in trdp_mdRecvUDPPacket.

**Comment by T12z** [comment]
As you probably read on the front page of the repo, I am not maintaining the code anymore. Please report this upstream.

You may also want to report the version of LWIP, maybe also the µC architecture as it can make a noteworthy difference.
